export const REQUEST_CART_OUTLINE_API_RESPONSE =
  'REQUEST_CART_OUTLINE_API_RESPONSE,'
export const RECEIVE_CART_OUTLINE_API_RESPONSE =
  'RECEIVE_CART_OUTLINE_API_RESPONSE,'
export const ERROR_CART_OUTLINE_API_RESPONSE =
  'ERROR_CART_OUTLINE_API_RESPONSE,'
export const REQUEST_ADD_WISHLIST_API_RESPONSE =
  'REQUEST_ADD_WISHLIST_API_RESPONSE'
export const RECEIVE_ADD_WISHLIST_API_RESPONSE =
  'RECEIVE_ADD_WISHLIST_API_RESPONSE'
export const ERROR_ADD_WISHLIST_API_RESPONSE = 'ERROR_ADD_WISHLIST_API_RESPONSE'
export const REQUEST_REMOVE_WISHLIST_API_RESPONSE =
  'REQUEST_REMOVE_WISHLIST_API_RESPONSE'
export const RECEIVE_REMOVE_WISHLIST_API_RESPONSE =
  'RECEIVE_REMOVE_WISHLIST_API_RESPONSE'
export const ERROR_REMOVE_WISHLIST_API_RESPONSE =
  'ERROR_REMOVE_WISHLIST_API_RESPONSE'
export const RESET_TOAST_MESSAGE = 'RESET_TOAST_MESSAGE'
