export const REQUEST_PLP_API_RESPONSE = "REQUEST_PLP_API_RESPONSE";
export const RECEIVE_PLP_API_RESPONSE = "RECEIVE_PLP_API_RESPONSE";
export const ERROR_PLP_API_RESPONSE = "ERROR_PLP_API_RESPONSE";
export const UPDATE_FACET_VALUE = "UPDATE_FACET_VALUE";
export const RESET_ALL_FACETS = "RESET_ALL_FACETS";
export const APPLY_NEW_FACETS = "APPLY_NEW_FACETS";
